import { ScrollViewStyleReset } from "expo-router/html";
import type { PropsWithChildren } from "react";

import { DarkColorEnum, LightColorEnum } from "@/theme/enums/color.enums";
import { THEME_MODE_STORAGE_KEY } from "@/theme/theme.constant";

/**
 * Web-only root HTML shell (Expo Router, static output). Paints the background
 * and sets the browser `color-scheme` (native form controls, scrollbars) before
 * React mounts, honoring the persisted theme mode so a manual override doesn't
 * flash the wrong theme. Dark is the default (no stored choice); "auto" follows
 * `prefers-color-scheme`. Native (iOS/Android) is handled by
 * `userInterfaceStyle: "automatic"` in app.json + ThemeProvider.
 */

// The stored mode is applied as `data-theme` on <html> by the blocking script
// below, before first paint. Unset/unknown falls back to dark (the default).
const themeCss = `
:root { color-scheme: dark; }
body { background-color: ${DarkColorEnum.bg}; }
:root[data-theme="light"] { color-scheme: light; }
:root[data-theme="light"] body { background-color: ${LightColorEnum.bg}; }
@media (prefers-color-scheme: light) {
  :root[data-theme="auto"] { color-scheme: light; }
  :root[data-theme="auto"] body { background-color: ${LightColorEnum.bg}; }
}
`;

// AsyncStorage's web backend is localStorage with the raw key, so the persisted
// mode is readable synchronously here.
const themeScript = `
try {
  document.documentElement.dataset.theme =
    localStorage.getItem(${JSON.stringify(THEME_MODE_STORAGE_KEY)}) || "dark";
} catch (e) {}
`;

// expo-router's web-modal stylesheet (the `EXPO_UNSTABLE_WEB_MODAL` overlay that
// backs `presentation: "formSheet" | "modal"` routes). Its CSS module is imported
// inside the *lazy* modal chunk, and — same bug as the Leaflet CSS above — Metro
// doesn't extract async-chunk CSS in the production web export, so it's never
// linked in `output: "server"`. Without it the drawer has no positioning
// (`position: static`) and renders off-screen below the fold: the filter sheet
// "doesn't open" in prod while working in dev (where Metro injects it at runtime).
//
// Verbatim copy of `node_modules/expo-router/assets/modal.module.css` as emitted
// by the build (`dist/.../css/modal.module-*.css`). The `fApBhq_` prefix is the
// CSS-module class hash — deterministic for a given expo-router version (verified
// identical in the staging and local bundles), so it matches the class names the
// modal JS references. RE-SYNC THIS after an expo SDK / expo-router upgrade if the
// web filter sheet renders off-screen again (the hash changes with the file).
// Web fonts. On web the three families are NOT loaded through expo-font (see
// `fonts.constant.web.ts`); their `@font-face` is declared here instead, so the
// CSS ships in the initial HTML rather than being injected by a lazy chunk.
//
// Each family has two faces: the real self-hosted WOFF2 (`public/fonts/*.woff2`,
// served at `/fonts/*` — stable URLs, decoupled from Metro's content hashing),
// with `font-display: swap`; and a **metric-matched fallback** whose
// `size-adjust` / `*-override` descriptors make a local system font (Arial /
// Courier New) occupy the exact box the real font will, so the swap causes **no
// layout shift (CLS)**. `fonts.constant.web.ts` sets each `FONTS` value to the
// stack `"<real>", "<… Fallback>", <system>` so the browser paints the adjusted
// fallback until the WOFF2 arrives.
//
// The override percentages are generated by `@capsizecss/core`'s
// `createFontStack` from each font's own metrics (unpacked from the TTF) against
// the fallback's metrics. RE-GENERATE them if a font file is swapped (a new
// weight or a family change) — they're specific to these exact files.
const fontFacesCss = `
@font-face{font-family:"Archivo_800ExtraBold";src:url(/fonts/Archivo_800ExtraBold.woff2) format("woff2");font-display:swap}
@font-face{font-family:"Archivo ExtraBold Fallback";src:local("Arial"),local("ArialMT");ascent-override:79.0734%;descent-override:18.9128%;line-gap-override:0%;size-adjust:111.0361%}
@font-face{font-family:"HankenGrotesk_400Regular";src:url(/fonts/HankenGrotesk_400Regular.woff2) format("woff2");font-display:swap}
@font-face{font-family:"Hanken Grotesk Fallback";src:local("Arial"),local("ArialMT");ascent-override:99.0668%;descent-override:30.0173%;line-gap-override:0%;size-adjust:100.9419%}
@font-face{font-family:"SpaceMono_400Regular";src:url(/fonts/SpaceMono_400Regular.woff2) format("woff2");font-display:swap}
@font-face{font-family:"Space Mono Fallback";src:local("Courier New"),local("CourierNewPSMT");ascent-override:109.8218%;descent-override:35.3979%;size-adjust:101.9834%}
`;

const modalCss = `.fApBhq_modal{pointer-events:auto;border:var(--expo-router-modal-border,none);box-sizing:border-box;will-change:transform;flex-direction:column;flex:1;display:flex;overflow:auto}.fApBhq_overlay{background-color:var(--expo-router-modal-overlay-background,#00000040);position:fixed;inset:0}@media (width>=768px){.fApBhq_modal{z-index:50;width:var(--expo-router-modal-width,83vw);min-width:var(--expo-router-modal-min-width,auto);max-width:var(--expo-router-modal-max-width,min(936px,83vw));height:var(--expo-router-modal-height,79dvh);max-height:min(var(--expo-router-modal-height,min(586px,79dvh)),calc(100dvh - 2rem));min-height:min(var(--expo-router-modal-min-height,var(--expo-router-modal-height,min(586px,79dvh))),calc(100dvh - 2rem));filter:var(--expo-router-modal-shadow,drop-shadow(0 10px 8px #0000000a)drop-shadow(0 4px 3px #0000001a));outline:none;position:relative;overflow:auto}.fApBhq_modalWrap>.fApBhq_modal{pointer-events:auto}}.fApBhq_drawerContent{outline:none;flex-direction:column;height:100%;display:flex;position:fixed;bottom:0;left:0;right:0}body>.fApBhq_transparentDrawerContent{outline:none;flex-direction:column;height:100%;animation:none;display:flex;position:fixed;bottom:0;left:0;right:0}@media (width>=768px){.fApBhq_drawerContent{pointer-events:box-none;max-height:100%}}.fApBhq_modal::-webkit-scrollbar{width:0;height:0}.fApBhq_modal::-webkit-scrollbar-thumb{background:0 0}.fApBhq_modalBody{box-sizing:border-box;flex:1;display:flex;overflow:auto}.fApBhq_drawerContent .fApBhq_modal[data-presentation=formSheet],.fApBhq_drawerContent .fApBhq_modal[data-presentation=containedModal]{box-shadow:none;filter:none;border-radius:inherit;width:100%;max-width:none;min-height:auto;max-height:none;position:relative;transform:none}.fApBhq_drawerContent .fApBhq_modal[data-presentation=modal],.fApBhq_drawerContent .fApBhq_modal[data-presentation=fullScreenModal]{width:var(--expo-router-modal-width,83vw);min-width:var(--expo-router-modal-min-width,auto);max-width:var(--expo-router-modal-max-width,min(936px,83vw));filter:var(--expo-router-modal-shadow,drop-shadow(0px 25px 50px #0000004d));border-radius:var(--expo-router-modal-border-radius,24px);margin:0;position:fixed;top:50%;left:50%;transform:translate(-50%,-50%)}.fApBhq_srOnly{display:none}`;

// Leaflet's layout CSS. On web it must be present for the map to render, but the
// `import "leaflet/dist/leaflet.css"` inside the *lazy* map chunk isn't linked in
// the production export (Metro drops async-chunk CSS — same bug as `modalCss`).
// It's self-hosted from the npm package in `public/leaflet/` (served same-origin
// at `/leaflet/leaflet.css`, like the fonts in `public/fonts/`), and injected by
// this tiny script rather than a synchronous `<link>`: a stylesheet inserted via
// JS is NOT render-blocking (the old unpkg `<link>` was — Lighthouse). The CSS is
// off the critical path (below-the-fold map, itself a lazy chunk). Keeping the
// file verbatim (with its `images/` beside it) means `url(images/…)` resolve to
// `/leaflet/images/…`. The files are committed but generated from the npm package
// by `bun run sync:leaflet` (scripts/copy-leaflet-assets.ts), run automatically by
// the `postinstall` hook (every `bun install`) and the `prestart` / `preweb` hooks
// (every `bun start` / `bun web`) — so a leaflet bump refreshes them; commit the diff.
const leafletCssLoader = `(function(){var l=document.createElement("link");l.rel="stylesheet";l.href="/leaflet/leaflet.css";document.head.appendChild(l)})()`;

export default function Root({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta name="color-scheme" content="dark light" />
        {/* Preload the display + body WOFF2 so the real font arrives sooner and
            the fallback→real swap flashes for less time. Mono is small-label-only,
            not preloaded. `crossOrigin` is required on font preloads even
            same-origin, or the preload is discarded and re-fetched. */}
        <link
          rel="preload"
          as="font"
          type="font/woff2"
          href="/fonts/Archivo_800ExtraBold.woff2"
          crossOrigin=""
        />
        <link
          rel="preload"
          as="font"
          type="font/woff2"
          href="/fonts/HankenGrotesk_400Regular.woff2"
          crossOrigin=""
        />
        {/* Self-hosted @font-face (real WOFF2 + metric-matched fallbacks) — see
            the `fontFacesCss` note above. */}
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: build-time constant, no user input */}
        <style dangerouslySetInnerHTML={{ __html: fontFacesCss }} />
        {/* Leaflet's layout CSS — self-hosted in `public/leaflet/`, loaded
            non-render-blocking via `leafletCssLoader` (not a synchronous `<link>`;
            the old unpkg one blocked render). The preload just starts the fetch
            sooner. See the `leafletCssLoader` note above. */}
        <link rel="preload" as="style" href="/leaflet/leaflet.css" />
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: build-time constant, no user input */}
        <script dangerouslySetInnerHTML={{ __html: leafletCssLoader }} />
        {/* Web-modal positioning CSS that Metro drops from the prod export — see
            the `modalCss` note above. Without it the filter sheet renders
            off-screen. */}
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: build-time constant, no user input */}
        <style dangerouslySetInnerHTML={{ __html: modalCss }} />
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: build-time constants, no user input */}
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: build-time constants, no user input */}
        <style dangerouslySetInnerHTML={{ __html: themeCss }} />
        {/* Keeps `position: fixed` / `100vh` scrolling correct with static web output. */}
        <ScrollViewStyleReset />
      </head>
      <body>{children}</body>
    </html>
  );
}
